# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0005_wearable_db_snr_customerreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearable_db',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
    ]
