# Generated by Django 2.2.6 on 2019-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_DailyDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(db_index=True, default='', max_length=500)),
                ('SNR_Title', models.CharField(db_index=True, default=None, max_length=1000, null=True)),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_PriceBefore', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_PriceAfter', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_Available', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000)),
                ('SNR_ImageURL', models.CharField(default=None, max_length=2000, null=True)),
                ('SNR_Active', models.NullBooleanField(default=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(db_index=True, default='', max_length=500)),
                ('SNR_Title', models.CharField(db_index=True, default=None, max_length=1000, null=True)),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_PriceBefore', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_PriceAfter', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_Available', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000)),
                ('SNR_ImageURL', models.CharField(default=None, max_length=2000, null=True)),
                ('SNR_Active', models.BooleanField(default=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image20px', models.CharField(max_length=255, null=True)),
                ('image40px', models.CharField(max_length=255, null=True)),
                ('image60px', models.CharField(max_length=255, null=True)),
                ('image80px', models.CharField(max_length=255, null=True)),
                ('image100px', models.CharField(max_length=255, null=True)),
                ('prefer', models.IntegerField(blank=True, default=100, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='merchantscoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image20px', models.CharField(max_length=255, null=True)),
                ('image40px', models.CharField(max_length=255, null=True)),
                ('image60px', models.CharField(max_length=255, null=True)),
                ('image80px', models.CharField(max_length=255, null=True)),
                ('image100px', models.CharField(max_length=255, null=True)),
                ('prefer', models.IntegerField(blank=True, default=100, null=True)),
                ('count', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
