# Generated by Django 2.2.6 on 2019-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0002_active_dailydeals_dailydeals_merchants_merchantscoupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductsCoupons_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Title', models.CharField(default=None, max_length=1000, null=True)),
                ('SNR_Description', models.TextField(default=None, null=True)),
                ('SNR_Available', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_URl_Code', models.BooleanField(default=False)),
                ('SNR_CouponCode_url', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Discount', models.CharField(default=None, max_length=100, null=True)),
                ('SNR_Expire', models.DateField(blank=True, default='', null=True)),
                ('SNR_Expire_Status', models.BooleanField(default=False)),
                ('SNR_Active', models.NullBooleanField(default=False)),
                ('site', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Manual', models.NullBooleanField(default=False)),
            ],
            options={
                'unique_together': {('SNR_CouponCode_url',)},
            },
        ),
        migrations.CreateModel(
            name='AllProductsCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Title', models.CharField(default=None, max_length=1000, null=True)),
                ('SNR_Description', models.TextField(default=None, null=True)),
                ('SNR_Available', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_URl_Code', models.BooleanField(default=False)),
                ('SNR_CouponCode_url', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Discount', models.CharField(default=None, max_length=100, null=True)),
                ('SNR_Expire', models.DateField(blank=True, default='', null=True)),
                ('SNR_Expire_Status', models.BooleanField(default=False)),
                ('SNR_Active', models.NullBooleanField(default=False)),
                ('site', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Manual', models.NullBooleanField(default=False)),
            ],
            options={
                'unique_together': {('SNR_CouponCode_url',)},
            },
        ),
    ]
