# Generated by Django 3.2 on 2023-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0004_allproducts_ebayindividualurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_dailydeals',
            name='SNR_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allproductscoupons',
            name='Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproductscoupons',
            name='SNR_Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproductscoupons_backup',
            name='Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproductscoupons_backup',
            name='SNR_Active',
            field=models.BooleanField(default=False),
        ),
    ]
