# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='SNR_ProductURL',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
    ]
