# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20171013_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='SNR_ProductTitle',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_Available',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_Brand',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_CustomerReviews',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_Description',
            field=models.CharField(default=' ', max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_ImageURL',
            field=models.CharField(default=' ', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_SKU',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='SNR_ProductURL',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
