# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20171103_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_ImageURL')]),
        ),
    ]
