# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0006_auto_20171219_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(db_index=True, default=' ', max_length=200, null=True)),
                ('Blog_Meta', models.CharField(db_index=True, default=' ', max_length=200, null=True)),
                ('Blog_Detail', models.CharField(db_index=True, default=' ', max_length=5000, null=True)),
                ('Blog_ImagePath', models.CharField(db_index=True, default=' ', max_length=200, null=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
