# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_blog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_ImageURL', 'SNR_Date')]),
        ),
    ]
