# Generated by Django 2.2 on 2021-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_wishlist_snr_isshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='SNR_item_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
