# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20170713_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_db',
            name='SNR_CustomerReviews',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
