# Generated by Django 2.2 on 2019-05-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='SNR_Available',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_Brand',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_Description',
            field=models.CharField(default=' ', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_ImageURL',
            field=models.CharField(default=' ', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_ProductURL',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_SKU',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
    ]
