# Generated by Django 3.2 on 2023-04-18 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('profile_photo', models.CharField(default='', max_length=1000, verbose_name='Profile Photo (URL)')),
                ('caption', models.CharField(default='', max_length=500, verbose_name='Caption')),
                ('video', models.FileField(default='', upload_to='tube_videos/', verbose_name='Video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shorts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
