# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_userdetails_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='Policy',
        ),
    ]
