# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0004_sendfriends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendfriends',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
