# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0005_auto_20170720_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfriends',
            name='sharedlink',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
    ]
