# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0006_sendfriends_sharedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendfriends',
            name='sharedlink',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
