# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0007_auto_20170720_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfriends',
            name='SNR_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        # migrations.RemoveField(
        #     model_name='sendfriends',
        #     name='SNR_Date',
        # ),
        # migrations.RemoveField(
        #     model_name='userdetails',
        #     name='SNR_Date',
        # ),
    ]