# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0008_sendfriends_snr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('isSend', models.BooleanField(default=False)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='SNR_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),

    ]
