# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0009_auto_20170818_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendfriends',
            name='SNR_Date',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='SNR_Date',
        ),
    ]
