# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0010_auto_20170818_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('isValid', models.BooleanField(default=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
