# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0011_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='link',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
