# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0012_subscribers_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='link',
        ),
        migrations.AddField(
            model_name='reset_password',
            name='link',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
