# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0013_auto_20170829_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_password',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
