# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0015_auto_20170829_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_password',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
