# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-09 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0016_auto_20170829_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset_password',
            name='Code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
