# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0017_reset_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='SeceretKey',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
