# Generated by Django 3.2 on 2023-08-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credential', '0018_auto_20180416_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='ISConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='snr_uid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='social_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='social_provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Available', models.CharField(max_length=255, null=True)),
                ('Count', models.IntegerField(blank=True, default=0)),
                ('Product', models.CharField(blank=True, max_length=500, null=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
