# Generated by Django 3.2 on 2023-04-18 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.PositiveIntegerField(default='', verbose_name='Commented By')),
                ('username', models.CharField(default='', max_length=50, verbose_name='Username')),
                ('profile_photo', models.CharField(blank=True, default='', max_length=1000, verbose_name='Profile Photo (URL)')),
                ('comment_text', models.TextField(default='', max_length=500, verbose_name='Comment Text')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('profile_photo', models.CharField(default='', max_length=1000, verbose_name='Profile Photo (URL)')),
                ('post_text', models.TextField(default='', max_length=1000, verbose_name='Post Text')),
                ('country', models.CharField(default='', max_length=100, verbose_name='Country')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('area_address', models.CharField(default='', max_length=200, verbose_name='Area Address')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhood_posts', to='social.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.CharField(default='', max_length=50, verbose_name='Liked By')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.CharField(default='', max_length=250, verbose_name='Followed By')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_followers', to='social.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(default='', upload_to='post_media/', verbose_name='Media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_list', to='social.post')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.CharField(default='', max_length=50, verbose_name='Liked By')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='social.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_list', to='social.post'),
        ),
    ]
