# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-22 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_ProductID', models.CharField(default='', max_length=500)),
                ('SNR_Username', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_Brand', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_UPC', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Review', models.CharField(default=None, max_length=8000, null=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
