# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0002_userreviews_snr_titlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='SNR_StartRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
    ]
