# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0003_userreviews_snr_startrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviews',
            old_name='SNR_StartRating',
            new_name='SNR_StarRating',
        ),
    ]
