# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0004_auto_20170805_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviews',
            name='SNR_StarRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
