# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0005_auto_20170805_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_ProductID', models.CharField(default='', max_length=500)),
                ('SNR_UPC', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Review', models.TextField(default=None, null=True)),
                ('SNR_Category', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_VendorName', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_StarRating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
