# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0006_vendorreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviews',
            name='SNR_Review',
            field=models.CharField(default=None, max_length=10000000, null=True),
        ),
    ]
