# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0007_auto_20170823_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviews',
            name='SNR_Review',
            field=models.TextField(default=None, null=True),
        ),
    ]
