# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0008_auto_20170823_1407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorreviews',
            unique_together=set([('SNR_ProductID',)]),
        ),
    ]
