# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0009_auto_20170824_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorreviews',
            unique_together=set([('SNR_ProductID', 'SNR_Review')]),
        ),
    ]
