# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0011_auto_20171116_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorreviewsscore',
            name='SNR_ProductTitle',
        ),
        migrations.AddField(
            model_name='vendorreviews',
            name='SNR_ProductTitle',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
