# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0013_auto_20171122_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorreviewsscore',
            old_name='SNR_ProductID',
            new_name='reviews',
        ),
        migrations.AlterUniqueTogether(
            name='vendorreviewsscore',
            unique_together=set([]),
        ),
    ]
