# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0014_auto_20171122_0626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreviews',
            unique_together=set([('SNR_Username', 'SNR_TitleReview', 'SNR_Review', 'SNR_StarRating', 'SNR_ProductID')]),
        ),
    ]
