# Generated by Django 2.2 on 2020-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0016_emailalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNamesandImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_image', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(max_length=100)),
            ],
        ),
    ]
