# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_auto_20170705_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop_db',
            name='SNR_CustomerReviews',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
