# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170614_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carselectronics',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL')]),
        ),
    ]
