# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170615_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videogames',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_Price')]),
        ),
    ]
