# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170617_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applinces',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_Price')]),
        ),
    ]
