# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20170619_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cams',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_ImageURL', 'SNR_ModelNo', 'SNR_Title')]),
        ),
    ]
