# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170619_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toys',
            unique_together=set([('SNR_SKU', 'SNR_ModelNo', 'SNR_ImageURL', 'SNR_ProductURL')]),
        ),
    ]
