# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-06 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170623_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applinces',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='audio',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='cams',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='carselectronics',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='computersoftware',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='officesupply',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='smarthomes',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='toys',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='tv',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50),
        ),
    ]
