# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170711_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogames',
            name='SNR_Price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=50),
        ),
    ]
