# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170713_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cams',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_ImageURL', 'SNR_ModelNo', 'SNR_Title', 'SNR_Price')]),
        ),
    ]
