# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20170911_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applinces',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applinces',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='applinces',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cams',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cams',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='carselectronics',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carselectronics',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flowerandplants',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flowerandplants',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flowerandplants',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='healthandfitness',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='healthandfitness',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='healthandfitness',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homeandgarden',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homeandgarden',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeandgarden',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officesupply',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officesupply',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='officesupply',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sportinggoods',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sportinggoods',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sportinggoods',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='SNR_ModelNo',
            field=models.CharField(db_index=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=' ', max_length=1000, null=True),
        ),
    ]
