# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20170911_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(default='', max_length=500)),
                ('SNR_Title', models.CharField(default=None, max_length=1000, null=True)),
                ('SNR_ModelNo', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Brand', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_UPC', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_CustomerReviews', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Available', models.CharField(default=None, max_length=50, null=True)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000)),
                ('SNR_ImageURL', models.CharField(default=None, max_length=2000, null=True)),
                ('SNR_Description', models.CharField(default=None, max_length=8000, null=True)),
                ('SNR_isShow', models.BooleanField(default=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
