# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_allproducts_snr_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Available',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Category',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_SKU',
            field=models.CharField(db_index=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Title',
            field=models.CharField(db_index=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_UPC',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_isShow',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
