# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20171213_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(db_index=True, default='', max_length=500)),
                ('SNR_Title', models.CharField(db_index=True, default=None, max_length=1000, null=True)),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_PriceBefore', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_PriceAfter', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_Available', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000)),
                ('SNR_ImageURL', models.CharField(default=None, max_length=2000, null=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
