# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_dailydeals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydeals',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_Available', 'SNR_Date')]),
        ),
    ]
