# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20180110_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydeals',
            unique_together=set([('SNR_SKU', 'SNR_ProductURL', 'SNR_Available', 'SNR_PriceBefore', 'SNR_PriceAfter')]),
        ),
    ]
