# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20180111_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='SNR_PriceBefore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
    ]
