# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_allproducts_snr_pricebefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='SNR_Condition',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='SNR_SubCategory',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
    ]
