# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20180129_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Review_Title', models.CharField(default='', max_length=500)),
                ('SNR_Review_Author', models.CharField(default='', max_length=500)),
                ('SNR_Review_Body', models.CharField(default='', max_length=500)),
                ('SNR_Review_Stars', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Review_UP', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Review_Down', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.AllProducts')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product_reviews',
            unique_together=set([('Product', 'SNR_Review_Title', 'SNR_Review_Body')]),
        ),
    ]
