# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20180207_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_PriceBefore',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=50),
        ),
    ]
