# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 06:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_product_reviews_snr_is_snr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Review_AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Review_Info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.AllProducts', unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='product_review_ai',
            index=django.contrib.postgres.indexes.GinIndex(fields=['SNR_Review_Info'], name='products_pr_SNR_Rev_589398_gin'),
        ),
    ]
