# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 06:23
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20180227_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product_review_ai',
            name='products_pr_SNR_Rev_589398_gin',
        ),
        migrations.AddIndex(
            model_name='product_review_ai',
            index=django.contrib.postgres.indexes.GinIndex(fields=['SNR_Review_Info'], name='SNR_Review_Info_gin'),
        ),
    ]
