# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_auto_20180410_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_ID', models.IntegerField(unique=True)),
                ('SNR_CatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_SubCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_TriCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_TetCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_PentCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_HexCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_HeptCatName', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
