# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_main_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_ID', models.IntegerField(null=True, unique=True)),
                ('SNR_SourceCatName', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
