# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_allproducts_snr_category_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='SNR_Category_Main',
        ),
    ]
