# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_remove_allproducts_snr_category_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='SNR_CatID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='SNR_MainCatID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='SNR_SubCatID',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
