# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_auto_20181023_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='HeptCat_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='HexCat_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='MainCat_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='PentCat_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='SubCat_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='TetCat_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='TriCat_ID',
            field=models.IntegerField(null=True),
        ),
    ]
