# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_auto_20181025_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProductsPartition',
        ),
    ]
