# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_allproductspartition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_reviews',
            name='SNR_Review_Stars',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
