# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_auto_20181119_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProductsPartition',
        ),
    ]
