# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_auto_20181207_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(db_index=True, default='', max_length=500)),
                ('SNR_Title', models.CharField(db_index=True, default=None, max_length=1000, null=True)),
                ('SNR_ModelNo', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Brand', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_UPC', models.CharField(db_index=True, default=None, max_length=500, null=True)),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_CatID', models.IntegerField(default=0, null=True)),
                ('SNR_SubCatID', models.IntegerField(default=0, null=True)),
                ('SNR_MainCatID', models.IntegerField(default=0, null=True)),
                ('SNR_SubCategory', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_Condition', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_PriceBefore', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=50)),
                ('SNR_Price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50)),
                ('SNR_CustomerReviews', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Available', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000)),
                ('SNR_ImageURL', models.CharField(default=None, max_length=2000, null=True)),
                ('SNR_Description', models.CharField(default=None, max_length=8000, null=True)),
                ('SNR_isShow', models.BooleanField(db_index=True, default=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='allproductsdata',
            unique_together=set([('SNR_Title', 'SNR_Available')]),
        ),
    ]
