# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_auto_20181210_1144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allproductspartition',
            unique_together=set([('SNR_Title', 'SNR_Available', 'id')]),
        ),
    ]
