# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_auto_20181211_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='SNR_SourceSubCatName',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
