# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_categorymapping_snr_sourcesubcatname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allproducts',
            unique_together=set([('SNR_Title', 'SNR_Available')]),
        ),
    ]
