# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_auto_20181213_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Description',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_ImageURL',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
