# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_amazonurls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonURLs',
        ),
    ]
