# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_amazonproxies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproxies',
            name='count',
            field=models.IntegerField(max_length=200),
        ),
    ]
