# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0083_auto_20190328_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonproxies',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='amazonproxies',
            old_name='Proxy',
            new_name='proxy',
        ),
    ]
