# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_auto_20190328_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonurls',
            old_name='status',
            new_name='status_scrape',
        ),
        migrations.AddField(
            model_name='amazonurls',
            name='status_range',
            field=models.BooleanField(default=False),
        ),
    ]
