# Generated by Django 2.2 on 2019-05-28 05:09

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_auto_20190403_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat', models.CharField(max_length=200)),
                ('SubCat', models.CharField(max_length=200)),
                ('SubSubCat', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('status_scrape', models.BooleanField(default=False)),
                ('status_range', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product_review_ai',
            name='products_pr_SNR_Rev_589398_gin',
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Description',
            field=models.CharField(default=None, max_length=50000, null=True),
        ),
        migrations.AddIndex(
            model_name='product_review_ai',
            index=django.contrib.postgres.indexes.GinIndex(fields=['SNR_Review_Info'], name='SNR_Review_Info_gin'),
        ),
    ]
