# Generated by Django 2.2 on 2019-05-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_auto_20190528_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayurls',
            name='SubSubSubCat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
