# Generated by Django 2.2 on 2019-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_ebayurls_subsubsubcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayIndividualURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(default='', max_length=500)),
                ('SNR_PriceBefore', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50)),
                ('SNR_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000, unique=True)),
                ('SNR_CustomerReviews', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('SNR_Title', models.CharField(default=None, max_length=1000, null=True)),
                ('status_scrape', models.BooleanField(default=False)),
            ],
        ),
    ]
