# Generated by Django 2.2 on 2019-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_ebayindividualurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayindividualurls',
            name='Cat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ebayindividualurls',
            name='SubCat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ebayindividualurls',
            name='SubSubCat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ebayindividualurls',
            name='SubSubSubCat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
