# Generated by Django 2.2 on 2019-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_auto_20190528_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayurls',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebayurls',
            name='count_str',
            field=models.CharField(default='', max_length=500),
        ),
    ]
