# Generated by Django 2.2 on 2019-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_auto_20190529_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproductspartition',
            name='SNR_Description',
            field=models.CharField(default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='allproductspartition',
            name='SNR_ImageURL',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
