# Generated by Django 2.2 on 2019-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_merchants'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='prefer',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
