# Generated by Django 2.2 on 2019-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_merchants_prefer'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='SNR_Description_Mobile',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='allproductspartition',
            name='SNR_Description_Mobile',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
