# Generated by Django 2.2 on 2019-08-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_auto_20190801_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allproducts',
            unique_together={('SNR_Title', 'SNR_Available', 'SNR_ProductURL')},
        ),
        migrations.AlterUniqueTogether(
            name='allproductspartition',
            unique_together={('SNR_Title', 'SNR_Available', 'id', 'SNR_ProductURL')},
        ),
    ]
