# Generated by Django 2.2 on 2019-08-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_ebayindividualurls_status_error'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ebayindividualurls',
            unique_together={('SNR_Title', 'SNR_SKU')},
        ),
    ]
