# Generated by Django 2.2 on 2019-08-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0098_auto_20190806_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeals',
            name='SNR_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Active_DailyDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_SKU', models.CharField(db_index=True, default='', max_length=500)),
                ('SNR_Title', models.CharField(db_index=True, default=None, max_length=1000, null=True)),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('SNR_PriceBefore', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_PriceAfter', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('SNR_Available', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('SNR_ProductURL', models.CharField(default='', max_length=2000)),
                ('SNR_ImageURL', models.CharField(default=None, max_length=2000, null=True)),
                ('SNR_Active', models.BooleanField(default=True)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('SNR_Title', 'SNR_Available', 'SNR_PriceAfter')},
            },
        ),
    ]
