# Generated by Django 2.2 on 2019-09-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_auto_20190830_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='active_dailydeals',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailydeals',
            unique_together=set(),
        ),
    ]
