# Generated by Django 2.2 on 2019-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0100_auto_20190903_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_dailydeals',
            name='SNR_Active',
            field=models.NullBooleanField(default=True),
        ),
    ]
