# Generated by Django 2.2 on 2019-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_auto_20190903_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='SNR_Review',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='SNR_Review_score',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='allproductspartition',
            name='SNR_Review',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='allproductspartition',
            name='SNR_Review_score',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
