# Generated by Django 2.2 on 2019-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0102_auto_20190916_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_categories',
            name='SNR_Cat_Image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
