# Generated by Django 2.2 on 2019-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_main_categories_snr_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
