# Generated by Django 2.2 on 2019-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0104_merchants_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayindividualurls',
            name='soup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
