# Generated by Django 2.2 on 2019-10-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_ebayindividualurls_soup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayUrlsBasedOnOnlyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=2000)),
                ('total', models.IntegerField(default=0)),
                ('until_sum', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('price_start', models.FloatField(blank=True, default=0)),
                ('price_end', models.FloatField(blank=True, default=0)),
                ('count', models.IntegerField(default=0)),
                ('count_str', models.CharField(default='', max_length=500)),
                ('status_scrape', models.BooleanField(default=False)),
                ('script_run', models.BooleanField(default=False)),
                ('totalpage', models.CharField(default='', max_length=500)),
                ('error', models.CharField(default='', max_length=500)),
                ('soup', models.TextField(blank=True, null=True)),
                ('status_latest', models.BooleanField(default=False)),
            ],
        ),
    ]
