# Generated by Django 2.2 on 2019-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0107_allproductscoupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproductscoupons',
            name='SNR_Active',
            field=models.NullBooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AllProductsCoupons_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_Title', models.CharField(default=None, max_length=1000, null=True)),
                ('SNR_Description', models.CharField(default=None, max_length=5000, null=True)),
                ('SNR_Available', models.CharField(default=None, max_length=200, null=True)),
                ('SNR_URl_Code', models.BooleanField(default=False)),
                ('SNR_CouponCode_url', models.CharField(default=None, max_length=500, null=True)),
                ('SNR_Discount', models.CharField(default=None, max_length=100, null=True)),
                ('SNR_Expire', models.DateField(blank=True, default='', null=True)),
                ('SNR_Expire_Status', models.BooleanField(default=False)),
                ('SNR_Active', models.NullBooleanField(default=False)),
            ],
            options={
                'unique_together': {('SNR_CouponCode_url',)},
            },
        ),
    ]
