# Generated by Django 2.2 on 2019-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0108_auto_20191010_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Description_Mobile',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='SNR_Review',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='allproductscoupons',
            name='SNR_Description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allproductscoupons_backup',
            name='SNR_Description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allproductspartition',
            name='SNR_Description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allproductspartition',
            name='SNR_Description_Mobile',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allproductspartition',
            name='SNR_Review',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
