# Generated by Django 2.2 on 2019-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_merchantscoupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantscoupons',
            name='count',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
