# Generated by Django 2.2 on 2019-10-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0111_merchantscoupons_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproductscoupons',
            name='Manual',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allproductscoupons',
            name='site',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allproductscoupons_backup',
            name='Manual',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allproductscoupons_backup',
            name='site',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
