# Generated by Django 2.2 on 2019-10-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0114_ebayindividualurls_soup'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_dailydeals',
            name='SNR_Description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailydeals',
            name='SNR_Description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
