# Generated by Django 2.2 on 2019-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0116_auto_20191101_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_dailydeals',
            name='SNR_Customer_Rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailydeals',
            name='SNR_Customer_Rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
