# Generated by Django 2.2 on 2020-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0118_active_vocation_vocation_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_CategoriesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_URL', models.CharField(db_index=True, default='', max_length=500, unique=True)),
                ('SNR_Available', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('SNR_ScrapeStatus', models.BooleanField(default=False)),
                ('SNR_Category', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('SNR_SubCategory', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('SNR_ErrorStatus', models.BooleanField(default=False)),
                ('SNR_Error', models.CharField(db_index=True, default=None, max_length=1000, null=True)),
                ('SNR_TotalRecords', models.IntegerField(default=0)),
                ('SNR_CurrentRecords', models.IntegerField(default=0)),
                ('SNR_PageNo', models.IntegerField(default=0)),
                ('SNR_CompleteStatus', models.BooleanField(default=False)),
                ('SNR_Date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
