# Generated by Django 2.2 on 2021-03-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0119_sub_categoriesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_dailydeals',
            name='SNR_CategoryURL',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='active_dailydeals',
            name='SNR_PageURL',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
