# Generated by Django 2.2 on 2021-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0121_auto_20210329_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_dailydeals',
            name='SNR_CategoryScrapeStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='active_dailydeals',
            name='SNR_PageScrapeStatus',
            field=models.BooleanField(default=False),
        ),
    ]
