# Generated by Django 3.2 on 2023-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0122_auto_20210329_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_dailydeals',
            name='SNR_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='active_vocation',
            name='SNR_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allproductscoupons',
            name='Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproductscoupons',
            name='SNR_Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproductscoupons_backup',
            name='Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproductscoupons_backup',
            name='SNR_Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_review_ai',
            name='SNR_Review_Info',
            field=models.JSONField(),
        ),
    ]
