# Generated by Django 3.2 on 2023-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0123_auto_20230125_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_dailydeals',
            name='SNR_Active',
            field=models.NullBooleanField(default=True),
        ),
    ]
