# Generated by Django 3.2 on 2023-03-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0124_alter_active_dailydeals_snr_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductsDuplicate',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
            ],
            bases=('products.allproducts',),
        ),
    ]
