# Generated by Django 3.2 on 2023-03-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0126_auto_20230328_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProductsDuplicateData',
        ),
    ]
