# Generated by Django 3.2 on 2023-04-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0128_allproductsduplicatedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_ID', models.IntegerField(unique=True)),
                ('SNR_CatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_Cat_Image', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_SubCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_SubCat_Image', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_TriCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_TetCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_PentCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_HexCatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_HeptCatName', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
