# Generated by Django 3.2 on 2023-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0129_vendors_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors_categories',
            name='items_count',
            field=models.IntegerField(default=None),
        ),
    ]
