# Generated by Django 3.2 on 2023-04-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0130_vendors_categories_items_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors_categories',
            name='Cat_ID',
        ),
    ]
