# Generated by Django 3.2 on 2023-05-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0132_categories_data_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories_Data_Transfer',
        ),
    ]
