# Generated by Django 3.2 on 2023-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0133_delete_categories_data_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Data_Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNR_CatName', models.CharField(default=None, max_length=255, null=True)),
                ('SNR_CatdataStatus', models.BooleanField(default=False)),
                ('items_count', models.IntegerField(blank=True, default=None)),
                ('shard_items_count', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
